from project.bakery import Bakery
#
bakery = Bakery("Friend")
print(bakery.add_food("Bread", "White", 2))
print(bakery.add_food("Bread", "Black", 4))
print(bakery.add_drink("Water", "Hisarya", 200, "ECO"))
print(bakery.add_drink("Water", "Devin", 200, "ECO"))
print(bakery.add_drink("Water", "Bankya", 200, "ECO"))
print(bakery.add_table("InsideTable", 1, 10))
print(bakery.add_table("InsideTable", 2, 5))
print(bakery.reserve_table(8))
print("-" * 20)
print(bakery.order_food(1, "White", "Black", "GGG"))
print("-" * 20)
print(bakery.order_drink(1, "Hisarya", "Devin", "Bachkovo"))
print("-" * 20)
print(bakery.get_free_tables_info())
print("-" * 20)
print(bakery.leave_table(1))
print("-" * 20)
print(bakery.get_total_income())

#
# bakery2 = Bakery("Pryateli")
# bakery2.add_food("Bread", "Bql", 1.1)
# bakery2.add_food("Bread", "Cheren", 1.5)
# bakery2.add_drink("Water", "Mineral", 100, "Devin")
# bakery2.add_table("InsideTable", 1, 10)
# bakery2.add_table("InsideTable", 2, 5)
#
# print(bakery2.reserve_table(1))
# print(bakery2.order_food(1, "Bql", "Cheren", "Ivan", "Pasta"))
# print("-------------------")
# print(bakery2.order_drink(1, "Mineral", "Devin"))
# print("-------------------")
# print(bakery2.leave_table(2))
# print("-------------------")
# print(bakery2.get_free_tables_info())
# print("-------------------")
# print(bakery2.get_total_income())