from project.controller import Controller

c = Controller()
print(c.add_aquarium("FreshwaterAquarium", "BIG"))
print(c.add_decoration("Ornament"))
print(c.insert_decoration("BIG", "Ornament"))
print(c.add_fish("BIG", "FreshwaterFish", "Ivan", "Mech", 2.5))
print(c.add_fish("BIG", "FreshwaterFish", "Gergi", "TARALEJ", 5))
print(c.add_fish("BIG", "FreshwaterFish", "GG", "TARALEJ", 5))
print(c.add_fish("BIG", "FreshwaterFish", "SW", "TARALEJ", 5))
print(c.add_fish("BIG", "FreshwaterFish", "Rw", "TARALEJ", 5))
print(c.add_fish("BIG", "FreshwaterFish", "FF", "TARALEJ", 5))
print(c.add_fish("BIG", "FreshwaterFish", "RFD", "TARALEJ", 5))
print(c.add_fish("BIG", "FreshwaterFish", "GWE", "TARALEJ", 50))
print(c.add_fish("BIG", "FreshwaterFish", "RBE", "TARALEJ", 5))
print(c.add_fish("BIG", "FreshwaterFish", "SW", "TARALEJ", 5))
print(c.add_fish("BIG", "FreshwaterFish", "Rw", "TARALEJ", 5))
print(c.add_fish("BIG", "FreshwaterFish", "Rw", "TARALEJ", 5))
print(c.add_fish("BIG", "SaltwaterFish", "SPAS", "BAH", 5))
print(c.add_fish("BIG", "FreshwaterFish", "Rw", "TARALEJ", 5))
print(c.add_fish("BIG", "FreshwaterFish", "Rw", "TARALEJ", 5))
print(c.feed_fish("BIG"))
print(c.report())
print(c.calculate_value("BIG"))